"""ClinVar Submitter -- Formats and submits evidence to ClinVar.

Generates ClinVar-format submission from Varis investigation results.
High-confidence predictions are submitted with structural evidence.
"""

import logging
import os
from datetime import date
from typing import Optional

import httpx

from varis.models.variant_record import VariantRecord

logger = logging.getLogger(__name__)

# ClinVar Submission API endpoints
CLINVAR_SUBMISSION_URL = "https://submit.ncbi.nlm.nih.gov/api/v1/submissions/"
CLINVAR_SUBMISSION_TEST_URL = (
    "https://submit.ncbi.nlm.nih.gov/apitest/v1/submissions/"
)

# Classification mapping from Varis internal terms to ClinVar terms
_CLASSIFICATION_MAP: dict[str, str] = {
    "likely_pathogenic": "Likely pathogenic",
    "likely_benign": "Likely benign",
}

# Classifications eligible for submission (NOT "uncertain")
_SUBMITTABLE_CLASSIFICATIONS = frozenset({"likely_pathogenic", "likely_benign"})

# Disclaimer appended to every submission comment
_DISCLAIMER = (
    "DISCLAIMER: This classification is based on computational structural "
    "evidence generated by Varis (Russell Genetics). All evidence codes are "
    "computational suggestions and have not been clinically adjudicated. This "
    "submission is intended to support professional variant curation, not "
    "replace it."
)


def format_clinvar_submission(
    variant_record: VariantRecord,
) -> Optional[dict]:
    """Format variant investigation into ClinVar submission format.

    Maps a fully-investigated VariantRecord into the dict structure
    expected by ClinVar's JSON submission API.  Returns None if the
    record does not meet submission gates (M5 incomplete, uncertain
    classification, or low model agreement).

    Args:
        variant_record: A VariantRecord with scoring completed.

    Returns:
        A dict formatted for ClinVar submission, or None if the record
        does not meet the quality gates for submission.
    """
    try:
        # -----------------------------------------------------------------
        # Gate 1: M5 must be completed
        # -----------------------------------------------------------------
        modules = variant_record.modules_completed or []
        if "M5" not in modules:
            logger.info(
                "Skipping ClinVar submission for %s: M5 not completed",
                variant_record.variant_id,
            )
            return None

        # -----------------------------------------------------------------
        # Gate 2: Classification must be submittable (not uncertain)
        # -----------------------------------------------------------------
        classification = variant_record.classification
        if classification not in _SUBMITTABLE_CLASSIFICATIONS:
            logger.info(
                "Skipping ClinVar submission for %s: classification=%s",
                variant_record.variant_id,
                classification,
            )
            return None

        # -----------------------------------------------------------------
        # Gate 3: Model agreement must be high
        # -----------------------------------------------------------------
        if variant_record.model_agreement != "high":
            logger.info(
                "Skipping ClinVar submission for %s: model_agreement=%s",
                variant_record.variant_id,
                variant_record.model_agreement,
            )
            return None

        # -----------------------------------------------------------------
        # Build HGVS coding with transcript prefix
        # -----------------------------------------------------------------
        hgvs_coding = variant_record.hgvs_coding or ""
        if variant_record.canonical_transcript and hgvs_coding:
            hgvs_coding = f"{variant_record.canonical_transcript}:{hgvs_coding}"

        # -----------------------------------------------------------------
        # Build evidence comment
        # -----------------------------------------------------------------
        comment = _build_evidence_comment(variant_record)

        # -----------------------------------------------------------------
        # Build method description
        # -----------------------------------------------------------------
        ensemble_version = variant_record.ensemble_version or "unknown"
        pipeline_version = variant_record.pipeline_version or "unknown"
        method_description = (
            f"Varis structural investigation pipeline ({pipeline_version}) "
            f"with ensemble model {ensemble_version}. Combines structural "
            f"analysis (stability, burial, contacts), evolutionary "
            f"conservation, and domain context into a gradient-boosted "
            f"tree ensemble for pathogenicity prediction."
        )

        # -----------------------------------------------------------------
        # Assemble submission dict
        # -----------------------------------------------------------------
        submission: dict = {
            "record_status": "update" if variant_record.clinvar_id else "novel",
            "variant_id": variant_record.variant_id,
            "gene_symbol": variant_record.gene_symbol,
            "hgvs_coding": hgvs_coding,
            "hgvs_protein": variant_record.hgvs_protein,
            "reference_build": variant_record.reference_build or "GRCh38",
            "chromosome": variant_record.clinvar_chrom,
            "position": variant_record.clinvar_pos,
            "ref_allele": variant_record.clinvar_ref,
            "alt_allele": variant_record.clinvar_alt,
            "clinical_significance": _CLASSIFICATION_MAP[classification],
            "date_last_evaluated": date.today().isoformat(),
            "collection_method": "research",
            "allele_origin": "germline",
            "affected_status": "not provided",
            "method_description": method_description,
            "comment": comment,
            "submitter": "Russell Genetics",
            "local_id": variant_record.variant_id,
        }

        # Include ClinVar accession if the variant already has one
        if variant_record.clinvar_id:
            submission["clinvar_accession"] = variant_record.clinvar_id

        logger.info(
            "Formatted ClinVar submission for %s: %s",
            variant_record.variant_id,
            submission["clinical_significance"],
        )
        return submission

    except Exception as e:
        logger.warning(
            "Failed to format ClinVar submission for %s: %s",
            getattr(variant_record, "variant_id", "unknown"),
            e,
        )
        return None


def submit_to_clinvar(
    submission: dict,
    dry_run: bool = True,
    use_test_endpoint: bool = True,
) -> dict:
    """Submit a formatted record to the ClinVar Submission API.

    Args:
        submission: Dict produced by format_clinvar_submission().
        dry_run: If True, return the payload without making an HTTP call.
        use_test_endpoint: If True, use the ClinVar test endpoint.

    Returns:
        A dict with status information:
        - dry_run: {"status": "dry_run", "variant_id": ..., "payload": ...}
        - missing key: {"status": "error", "variant_id": ..., "reason": ...}
        - success/failure from API: {"status": ..., "variant_id": ..., ...}
    """
    variant_id = submission.get("variant_id", "unknown")

    # -----------------------------------------------------------------
    # Dry run — return immediately
    # -----------------------------------------------------------------
    if dry_run:
        logger.info("Dry run submission for %s", variant_id)
        return {
            "status": "dry_run",
            "variant_id": variant_id,
            "payload": submission,
        }

    # -----------------------------------------------------------------
    # Check for API key
    # -----------------------------------------------------------------
    api_key = os.environ.get("CLINVAR_API_KEY")
    if not api_key:
        logger.warning(
            "Cannot submit %s: CLINVAR_API_KEY environment variable not set",
            variant_id,
        )
        return {
            "status": "error",
            "variant_id": variant_id,
            "reason": "CLINVAR_API_KEY environment variable not set",
        }

    # -----------------------------------------------------------------
    # POST to ClinVar API
    # -----------------------------------------------------------------
    url = (
        CLINVAR_SUBMISSION_TEST_URL
        if use_test_endpoint
        else CLINVAR_SUBMISSION_URL
    )

    try:
        with httpx.Client(timeout=60.0) as client:
            response = client.post(
                url,
                json={"actions": [{"type": "AddData", "data": submission}]},
                headers={
                    "Content-Type": "application/json",
                    "SP-API-KEY": api_key,
                },
            )
            response.raise_for_status()
            result = response.json()
            logger.info(
                "ClinVar submission succeeded for %s: %s",
                variant_id,
                result,
            )
            return {
                "status": "submitted",
                "variant_id": variant_id,
                "response": result,
            }
    except httpx.HTTPStatusError as e:
        logger.warning(
            "ClinVar API returned error for %s: %s %s",
            variant_id,
            e.response.status_code,
            e.response.text,
        )
        return {
            "status": "error",
            "variant_id": variant_id,
            "reason": f"HTTP {e.response.status_code}: {e.response.text}",
        }
    except Exception as e:
        logger.warning(
            "ClinVar submission failed for %s: %s", variant_id, e
        )
        return {
            "status": "error",
            "variant_id": variant_id,
            "reason": str(e),
        }


# =========================================================================
# HELPERS
# =========================================================================


def _build_evidence_comment(variant_record: VariantRecord) -> str:
    """Build the evidence summary comment for a ClinVar submission.

    Includes ensemble score with confidence interval, structural
    features, evidence tags, model version, and the mandatory
    disclaimer.

    Args:
        variant_record: A fully-scored VariantRecord.

    Returns:
        A multi-line evidence comment string.
    """
    parts: list[str] = []

    # Ensemble score with CI and agreement
    score = variant_record.score_ensemble
    lower = variant_record.confidence_lower
    upper = variant_record.confidence_upper
    agreement = variant_record.model_agreement or "unknown"
    if score is not None:
        ci_str = ""
        if lower is not None and upper is not None:
            ci_str = f" (95% CI: {lower:.2f}-{upper:.2f})"
        parts.append(
            f"Ensemble pathogenicity score: {score:.2f}{ci_str}, "
            f"model agreement: {agreement}."
        )

    # DDG value
    ddg = variant_record.ddg_mean
    if ddg is not None:
        parts.append(f"Predicted stability change (DDG): {ddg:.1f} kcal/mol.")

    # Burial category
    burial = variant_record.burial_category
    if burial is not None:
        parts.append(f"Burial category: {burial}.")

    # Domain info
    domain = variant_record.domain_name
    if domain is not None:
        criticality = variant_record.domain_criticality or "unknown"
        parts.append(f"Protein domain: {domain} (criticality: {criticality}).")

    # Conservation score
    conservation = variant_record.conservation_score
    if conservation is not None:
        parts.append(f"Conservation score: {conservation:.2f}.")

    # Secondary structure
    ss_name = variant_record.secondary_structure_name
    if ss_name is not None:
        parts.append(f"Secondary structure: {ss_name}.")

    # Evidence tags
    tags = variant_record.evidence_tags
    if tags:
        parts.append(
            f"Suggested computational evidence tags: {', '.join(tags)}."
        )

    # Model version
    ensemble_version = variant_record.ensemble_version or "unknown"
    parts.append(f"Ensemble model version: {ensemble_version}.")

    # Disclaimer
    parts.append(_DISCLAIMER)

    return " ".join(parts)
