"""Report Generator — Creates PDF and HTML clinical investigation reports.

Generates downloadable reports with structural evidence, SHAP explanations,
feature availability, and ACMG evidence summary.

Primary: WeasyPrint (HTML → PDF). Fallback: HTML-only export.
"""

import logging
from pathlib import Path
from typing import Optional

from varis.models.variant_record import VariantRecord

logger = logging.getLogger(__name__)


def generate_html_report(variant_record: VariantRecord) -> str:
    """Generate HTML clinical investigation report.

    Args:
        variant_record: Fully populated VariantRecord.

    Returns:
        Complete HTML string suitable for browser rendering or PDF conversion.
    """
    r = variant_record
    variant_id = r.variant_id or f"{r.gene_symbol}_{r.hgvs_protein}"
    classification_color = {
        "likely_pathogenic": "#dc2626",
        "uncertain": "#d97706",
        "likely_benign": "#16a34a",
    }.get(r.classification or "", "#6b7280")

    classification_label = (r.classification or "Not scored").replace("_", " ").title()

    # Build feature rows
    feature_rows = _build_feature_rows(r)

    # Build SHAP rows
    shap_rows = _build_shap_rows(r)

    # Build evidence tags
    evidence_html = _build_evidence_html(r)

    # Build provenance
    provenance_html = _build_provenance_html(r)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Varis Report — {variant_id}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         color: #1a1a2e; background: #fff; max-width: 800px; margin: 0 auto;
         padding: 40px 32px; font-size: 14px; line-height: 1.5; }}
  h1 {{ font-size: 22px; margin-bottom: 4px; }}
  h2 {{ font-size: 16px; margin: 24px 0 8px; padding-bottom: 4px;
        border-bottom: 2px solid #e5e7eb; color: #374151; }}
  .subtitle {{ color: #6b7280; font-size: 13px; margin-bottom: 20px; }}
  .badge {{ display: inline-block; padding: 4px 12px; border-radius: 4px;
            font-weight: 600; font-size: 13px; color: #fff; }}
  .score-row {{ display: flex; align-items: center; gap: 16px; margin: 12px 0; }}
  .score-big {{ font-size: 32px; font-weight: 700; }}
  .confidence {{ color: #6b7280; font-size: 13px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 8px 0; }}
  th {{ text-align: left; padding: 6px 8px; background: #f9fafb;
       border-bottom: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;
       text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #f3f4f6; font-size: 13px; }}
  .available {{ color: #16a34a; }}
  .missing {{ color: #dc2626; }}
  .tag {{ display: inline-block; padding: 2px 8px; margin: 2px;
          border-radius: 3px; font-size: 12px; background: #eff6ff;
          color: #1d4ed8; }}
  .shap-pos {{ color: #dc2626; font-weight: 600; }}
  .shap-neg {{ color: #16a34a; font-weight: 600; }}
  .provenance {{ color: #6b7280; font-size: 12px; margin-top: 32px;
                 padding-top: 16px; border-top: 1px solid #e5e7eb; }}
  .disclaimer {{ background: #fefce8; border: 1px solid #fde68a; padding: 12px;
                 border-radius: 4px; font-size: 12px; color: #92400e; margin: 16px 0; }}
  @media print {{ body {{ padding: 20px; }} }}
</style>
</head>
<body>

<h1>Variant Investigation Report</h1>
<div class="subtitle">{r.gene_symbol or ''} {r.hgvs_protein or ''} &mdash; {variant_id}</div>

<div class="disclaimer">
<strong>Research use only.</strong> This is a computational investigation report generated by
Varis. It is not a clinical diagnostic. Evidence tags are computational suggestions, not
clinical adjudications. Always consult qualified professionals for clinical decisions.
</div>

<h2>Classification</h2>
<div class="score-row">
  <div class="score-big">{_fmt(r.score_ensemble)}</div>
  <div>
    <span class="badge" style="background:{classification_color}">{classification_label}</span>
    <div class="confidence">
      95% CI: [{_fmt(r.confidence_lower)} &ndash; {_fmt(r.confidence_upper)}]
      &nbsp;&middot;&nbsp; Agreement: {r.model_agreement or 'N/A'}
    </div>
  </div>
</div>

{_individual_scores_html(r)}

<h2>Structural Features</h2>
<table>
<tr><th>Feature</th><th>Value</th><th>Status</th></tr>
{feature_rows}
</table>

<h2>SHAP Explanation</h2>
{shap_rows if shap_rows else '<p style="color:#6b7280">No SHAP data available.</p>'}

<h2>Evidence Tags</h2>
{evidence_html}

{provenance_html}

</body>
</html>"""


def generate_pdf_report(
    variant_record: VariantRecord, output_path: str
) -> Optional[str]:
    """Generate a PDF clinical investigation report.

    Uses WeasyPrint to convert the HTML report to PDF. Falls back to
    saving raw HTML if WeasyPrint is not installed.

    Args:
        variant_record: Fully populated VariantRecord.
        output_path: File path where the PDF (or HTML fallback) will be saved.

    Returns:
        Path to the generated file, or None on failure.
    """
    html = generate_html_report(variant_record)

    try:
        from weasyprint import HTML  # type: ignore[import-untyped]

        HTML(string=html).write_pdf(output_path)
        logger.info("PDF report generated: %s", output_path)
        return output_path
    except ImportError:
        logger.warning("WeasyPrint not installed — falling back to HTML report")
        html_path = str(Path(output_path).with_suffix(".html"))
        Path(html_path).write_text(html)
        logger.info("HTML report generated (PDF fallback): %s", html_path)
        return html_path
    except Exception as e:
        logger.error("Report generation failed: %s", e)
        return None


# =============================================================================
# HELPERS
# =============================================================================


def _fmt(value, decimals: int = 3) -> str:
    """Format a numeric value for display."""
    if value is None:
        return "—"
    return f"{value:.{decimals}f}"


def _build_feature_rows(r: VariantRecord) -> str:
    """Build HTML table rows for structural features."""
    features = [
        ("DDG (EvoEF2)", r.ddg_evoef2, "kcal/mol", r.ddg_available),
        ("DDG (FoldX)", r.ddg_foldx, "kcal/mol", r.ddg_available),
        ("DDG (PyRosetta)", r.ddg_pyrosetta, "kcal/mol", r.ddg_available),
        ("DDG Mean", r.ddg_mean, "kcal/mol", r.ddg_available),
        ("Solvent Accessibility", r.solvent_accessibility_relative, "relative", r.sasa_available),
        ("Burial Category", r.burial_category, None, r.sasa_available),
        ("Secondary Structure", r.secondary_structure_name, None, r.dssp_available),
        ("Contacts (WT)", r.contacts_wt, "count", r.contacts_available),
        ("H-bonds (WT)", r.hbonds_wt, "count", r.contacts_available),
        ("Packing Density", r.packing_density, None, r.contacts_available),
        ("Domain", r.domain_name, None, r.domain_available),
        ("Conservation Score", r.conservation_score, None, r.conservation_available),
        ("gnomAD Frequency", r.gnomad_frequency, None, r.gnomad_frequency is not None),
        ("AlphaMissense", r.alphamissense_score, None, r.alphamissense_score is not None),
        ("pLDDT at Site", r.mutation_site_plddt, None, r.plddt_available),
    ]

    rows = []
    null_reasons = r.null_reasons or {}
    for name, value, units, available in features:
        if value is not None:
            display = f"{value}" if units is None else f"{value} {units}"
            status = '<span class="available">&#10003;</span>'
        else:
            display = "—"
            field_key = name.lower().replace(" ", "_").replace("(", "").replace(")", "")
            reason = null_reasons.get(field_key, "")
            status = f'<span class="missing">&#10007; {reason}</span>' if not available else "—"
        rows.append(f"<tr><td>{name}</td><td>{display}</td><td>{status}</td></tr>")
    return "\n".join(rows)


def _build_shap_rows(r: VariantRecord) -> str:
    """Build SHAP explanation table."""
    if not r.shap_top_features:
        return ""

    rows = []
    for f in sorted(r.shap_top_features, key=lambda x: abs(x.get("shap", 0)), reverse=True):
        shap_val = f.get("shap", 0)
        css = "shap-pos" if shap_val > 0 else "shap-neg"
        direction = "+" if shap_val > 0 else ""
        feature_value = f.get("value", "—")
        rows.append(
            f'<tr><td>{f["feature"]}</td><td>{feature_value}</td>'
            f'<td class="{css}">{direction}{shap_val:.4f}</td></tr>'
        )

    return f"""<table>
<tr><th>Feature</th><th>Value</th><th>SHAP</th></tr>
{"".join(rows)}
</table>"""


def _build_evidence_html(r: VariantRecord) -> str:
    """Build evidence tags section."""
    tags = r.evidence_tags or []
    if not tags:
        return '<p style="color:#6b7280">No evidence tags generated.</p>'

    tag_labels = {
        "computational_support": "Computational Support (PP3-like)",
        "rarity_evidence": "Rarity Evidence (PM2-like)",
        "energetics_support": "Energetics Support (DDG-based)",
        "domain_context": "Critical Domain (PM1-like)",
    }
    html_tags = [f'<span class="tag">{tag_labels.get(t, t)}</span>' for t in tags]
    return (
        '<div style="margin:8px 0">'
        + " ".join(html_tags)
        + '</div><p style="color:#6b7280;font-size:12px">'
        "These are computational suggestions, not clinical adjudications.</p>"
    )


def _individual_scores_html(r: VariantRecord) -> str:
    """Build individual model scores HTML."""
    scores = []
    if r.score_catboost is not None:
        scores.append(f"CatBoost: {r.score_catboost:.3f}")
    if r.score_xgboost is not None:
        scores.append(f"XGBoost: {r.score_xgboost:.3f}")
    if r.score_lightgbm is not None:
        scores.append(f"LightGBM: {r.score_lightgbm:.3f}")

    if not scores:
        return ""
    return f'<p style="color:#6b7280;font-size:13px">{" &middot; ".join(scores)}</p>'


def _build_provenance_html(r: VariantRecord) -> str:
    """Build provenance footer."""
    sources = []
    if r.clinvar_id:
        sources.append("ClinVar")
    if r.uniprot_id:
        sources.append("UniProt")
    if r.structure_source:
        sources.append(r.structure_source.title())
    if r.gnomad_frequency is not None:
        sources.append("gnomAD")
    if r.alphamissense_score is not None:
        sources.append("AlphaMissense")
    if r.conservation_method:
        sources.append(r.conservation_method.replace("_", " ").title())

    modules_ok = ", ".join(r.modules_completed or []) or "None"
    modules_fail = ", ".join(r.modules_failed or []) or "None"

    return f"""<h2>Provenance</h2>
<div class="provenance">
  <p><strong>Data sources:</strong> {', '.join(sources) or 'None'}</p>
  <p><strong>Modules completed:</strong> {modules_ok}</p>
  <p><strong>Modules failed:</strong> {modules_fail}</p>
  <p><strong>Pipeline:</strong> {r.pipeline_version or 'N/A'}
     &middot; Schema: {r.record_schema_version}
     &middot; Ensemble: {r.ensemble_version or 'N/A'}</p>
  <p><strong>Timestamp:</strong> {r.investigation_timestamp or 'N/A'}</p>
  <p style="margin-top:8px">Generated by Varis &mdash; Russell Genetics</p>
</div>"""
